### ISSUE TITLE
Your website has error:404

### ISSUE THREAD

**Issue by ryewen** [visionjo/FIW_KRT#1]
I'm interested in Families in the wild, but smile-fiw.weebly.com is 404. How can I access your website and download?

**Comment by visionjo** [comment]
I am sorry. I just noticed this now for the first time.

FIW can be downloaded here, https://web.northeastern.edu/smilelab/fiw/download.html

Task 1 (of 3) has just opened up for the 3rd annual FIW data competition organized as a 2019 FG Data Challenge Workshop. Register and learn more here, https://competitions.codalab.org/competitions/20180

Let me know if you have any questions (also, I will add link to downloads in the README-- thank you for pointing this out).
